TPCartelera/Controllers/PeliculasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TPCartelera.DAL;
using TPCartelera.Filters;
using TPCartelera.Models;

namespace TPCartelera.Controllers
{
    [AuthFilter]
    public class PeliculasController : Controller
    {
        private CineContext db = new CineContext();

        // GET: Peliculas
        public ActionResult Index()
        {
            return View(db.Pelicula.ToList());
        }

        // GET: Peliculas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Peliculas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nombre,Sinopsis,Duracion,Imagen")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                db.Pelicula.Add(pelicula);
                db.SaveChanges();
                return RedirectToAction("Peliculas/Index");
            }

            return View(pelicula);
        }

        // GET: Peliculas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = db.Pelicula.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pelicula pelicula = db.Pelicula.Find(id);
            IEnumerable<Funcion> funciones = db.Funcion.Where(i => i.PeliculaID == pelicula.ID).ToList();
            if(funciones == null || funciones.Count() == 0)
            {
                db.Pelicula.Remove(pelicula);
                db.SaveChanges();
            }
            else
            {
                ViewBag.Error = "La pelicula esta programada / o siendo exhibida en una funcion";
                return View("Error");
            }
            return RedirectToAction("Index");
        }
        public ActionResult ElegirPelicula()
        {
            return View();
        }
    }
}

TPCartelera/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TPCartelera.DAL;
using TPCartelera.Models;

namespace TPCartelera.Controllers
{
    public class UsersController : Controller
    {
        private CineContext db = new CineContext();

        public ActionResult Login()
        {
            return View("Login");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string usuario, string contraseña)
        {
            try
            {
                var user = db.Users.Single(u => u.Usuario == usuario && u.Contraseña == contraseña);
                Session["Usuario"] = user;
                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                ViewBag.Error = "Usuario o contraseña incorrectos";
                return View("Error");
            }
            /*var user = db.Users.Single(u => u.Usuario == usuario);
            var pass = db.Users.Single(u => u.Contraseña == contraseña);
            if(user != null && pass != null)
            {
                Session["Usuario"] = usuario;
                return RedirectToAction("Index","Home");
            }
            else
            {
                return View("Error");
            }*/

        }
        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index","Home");
        }
    }
}

TPCartelera/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Gallovision </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Estilos.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" href="#">
            <img src="~/Content/Image/cine1.png" alt="logo" style="width:40px;">
        </a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Home")">Inicio</a>
            </li>
            @if (Session["Usuario"] == null)
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Login","Users")">Login</a>
                </li>
            }
            @if (Session["Usuario"] != null)
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Create","Funcions")"> Agregar Funcion</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","Funcions")"> Todas las funciones</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("ElegirPelicula","Peliculas")">Agregar Pelicula</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","Peliculas")">Todas las peliculas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Logout","Users")">Desconectar</a>
                </li>
            }

        </ul>
    </nav>
    <div> <br /></div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Gallovision</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>