TPCartelera/Models/Pelicula.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Collections;

namespace TPCartelera.Models
{
    public abstract class Pelicula 
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Sinopsis { get; set; }
        public int Duracion { get; set; }
        public string Imagen { get; set; }
    }
}

TPCartelera/Controllers/ComercialsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TPCartelera.DAL;
using TPCartelera.Filters;
using TPCartelera.Models;

namespace TPCartelera.Controllers
{
    [AuthFilter]
    public class ComercialsController : Controller
    {
        private CineContext db = new CineContext();

        public ActionResult Create()
        {
            return View();
        }

        // PO                                                                                               ST: Comercials/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection formCollection, HttpPostedFileBase img)
        {
            Comercial comercial = new Comercial();
            comercial.Nombre = formCollection["nombre"];
            comercial.Sinopsis = formCollection["sinopsis"];
            comercial.Duracion = Int32.Parse(formCollection["duracion"]);
            comercial.Actores = formCollection["actores"];
            comercial.Imagen = ConvertirABase64(img);
            if(comercial.Duracion > 360)
            {
                ViewBag.Error = "La duracion es mas de 360 minutos!";
                return View("Error");
            }
            db.Pelicula.Add(comercial);
            db.SaveChanges();
            return RedirectToAction("Index","Peliculas");
        }

        // GET: Comercials/Edit/5
        private string ConvertirABase64(HttpPostedFileBase img)
        {
            var fileStream = img.InputStream;
            var binaryReader = new BinaryReader(fileStream);
            var bytes = binaryReader.ReadBytes((Int32)fileStream.Length);
            var base64String = Convert.ToBase64String(bytes, 0, bytes.Length);
            return "data:image/png;base64," + base64String;
        }

    }
}

TPCartelera/Controllers/DocumentalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TPCartelera.DAL;
using TPCartelera.Filters;
using TPCartelera.Models;

namespace TPCartelera.Controllers
{
    [AuthFilter]
    public class DocumentalsController : Controller
    {
        private CineContext db = new CineContext();

        // GET: Documentals/Create
        public ActionResult Create()
        {
            return View(db.Tema.ToList());
        }

        // POST: Documentals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection formCollection, HttpPostedFileBase img)
        {
            Documental documental = new Documental();
            documental.Nombre = formCollection["nombre"];
            documental.Sinopsis = formCollection["sinopsis"];
            documental.Duracion = Int32.Parse(formCollection["Duracion"]);
            documental.Imagen = ConvertirABase64(img);
            documental.Tema = GetTemaById(Int32.Parse(formCollection["temaid"]));
            if (documental.Duracion > 360)
            {
                ViewBag.Error = "La duracion es mas de 360 minutos!";
                return View("Error");
            }
            db.Pelicula.Add(documental);
            db.SaveChanges();
            return RedirectToAction("Index", "Peliculas");
        }
        private string ConvertirABase64(HttpPostedFileBase img)
        {
            var fileStream = img.InputStream;
            var binaryReader = new BinaryReader(fileStream);
            var bytes = binaryReader.ReadBytes((Int32)fileStream.Length);
            var base64String = Convert.ToBase64String(bytes, 0, bytes.Length);
            return "data:image/png;base64," + base64String;
        }

        private Tema GetTemaById(int id)
        {
            var aux = db.Tema.ToList().Single(i => i.ID == id);
            return aux;
        }
       
    }
}

TPCartelera/Controllers/PeliculasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TPCartelera.DAL;
using TPCartelera.Filters;
using TPCartelera.Models;

namespace TPCartelera.Controllers
{
    [AuthFilter]
    public class PeliculasController : Controller
    {
        private CineContext db = new CineContext();

        // GET: Peliculas
        public ActionResult Index()
        {
            return View(db.Pelicula.ToList());
        }

        // GET: Peliculas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Peliculas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nombre,Sinopsis,Duracion,Imagen")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                db.Pelicula.Add(pelicula);
                db.SaveChanges();
                return RedirectToAction("Peliculas/Index");
            }

            return View(pelicula);
        }

        // GET: Peliculas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = db.Pelicula.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pelicula pelicula = db.Pelicula.Find(id);
            IEnumerable<Funcion> funciones = db.Funcion.Where(i => i.PeliculaID == pelicula.ID).ToList();
            if(funciones == null || funciones.Count() == 0)
            {
                db.Pelicula.Remove(pelicula);
                db.SaveChanges();
            }
            else
            {
                ViewBag.Error = "La pelicula esta programada / o siendo exhibida en una funcion";
                return View("Error");
            }
            return RedirectToAction("Index");
        }
        public ActionResult ElegirPelicula()
        {
            return View();
        }
    }
}

TPCartelera/Views/Peliculas/Create.cshtml
@model TPCartelera.Models.Pelicula

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pelicula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sinopsis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sinopsis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sinopsis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TPCartelera/Views/Peliculas/Delete.cshtml
@model TPCartelera.Models.Pelicula

@{
    ViewBag.Title = "Delete";
}

<h3>Esta seguro de que quiere borrar esta pelicula?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sinopsis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinopsis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duracion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duracion)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
            @Html.ActionLink("Volver Atras", "Index")
        </div>
    }
</div>

TPCartelera/Views/Peliculas/ElegirPelicula.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="card-columns">
        <div class="card">
            <div class="card-body">
                     <a href="@Url.Action("Create","Comercials")"> Comercial </a>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <a href="@Url.Action("Create","Documentals")">Documental</a>
            </div>
        </div>
    </div>
</body>
</html>

TPCartelera/Views/Peliculas/Index.cshtml
@model IEnumerable<TPCartelera.Models.Pelicula>

@{
    ViewBag.Title = "Todas las peliculas";
}
    <head>
        <link href="~/Content/Estilos.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    </head>
<h2>Todas las peliculas</h2>


<table class="table">
    <tr>
        <th>
            Tipo
        </th>
        <th>
            Nombre
        </th>
        <th>
            Sinopsis
        </th>
        <th>
            Duracion
        </th>
        <th>
            Actores / Tema
        </th>
        <th>
            Imagen
        </th>
    </tr>

    @foreach (var item in Model)
    {
        if (item is TPCartelera.Models.Comercial)
        {
            TPCartelera.Models.Comercial pelicula = item as TPCartelera.Models.Comercial;
        <tr>
            <td> Comercial </td>
            <td> @pelicula.Nombre</td>
            <td>@pelicula.Sinopsis</td>
            <td>@pelicula.Duracion minutos</td>
            <td>@pelicula.Actores</td>
            <td><img src="@pelicula.Imagen" alt="Alternate Text" class="img-thumbnail" style="background-size:auto" /></td>
            <td>@Html.ActionLink("Eliminar pelicula", "Delete", new { id = item.ID })</td>
        </tr>
        }
        else
        {
            TPCartelera.Models.Documental pelicula = item as TPCartelera.Models.Documental;
            <tr>
                <td>Documental</td>
                <td>@pelicula.Nombre</td>
                <td>@pelicula.Sinopsis</td>
                <td>@pelicula.Duracion Minutos</td>
                <td>@pelicula.Tema</td>
                <td><img src="@pelicula.Imagen" /></td>
                <td>@Html.ActionLink("Eliminar pelicula", "Delete", new { id = item.ID })</td>
            </tr>
        }

    }

</table>